export type Settings={width:number;height:number;coverWidth:number;ratio:string;format:string;quality:number;padding:number;frame:string;border:number;borderColor:string;radius:number;shadow:number;background:string;color:string;color2:string};
export type Shot={src:string;image:HTMLImageElement;index:number;label:string;url:string;angle:number;zoom:number;x:number;y:number};
export const defaults:Settings={width:1600,height:1200,coverWidth:1920,ratio:'4:3',format:'webp',quality:92,padding:0,frame:'none',border:0,borderColor:'#ffffff',radius:16,shadow:28,background:'solid',color:'#e8ecef',color2:'#bcced9'};
export function dimensions(o:Settings,i:number){const w=i===0?o.coverWidth:o.width;const r=i===0?16/9:o.ratio==='custom'?w/o.height:+o.ratio.split(':')[0]/+o.ratio.split(':')[1];return [w,Math.round(w/r)]}
export function draw(canvas:HTMLCanvasElement,s:Shot,o:Settings,preview=true){const[w,h]=dimensions(o,s.index),f=preview?Math.min(1,1100/w):1;canvas.width=Math.round(w*f);canvas.height=Math.round(h*f);const c=canvas.getContext('2d')!;c.scale(f,f);if(o.background!=='transparent'||o.format==='jpeg'){if(o.background==='gradient'){const g=c.createLinearGradient(0,0,w,h);g.addColorStop(0,o.color);g.addColorStop(1,o.color2);c.fillStyle=g}else c.fillStyle=o.color;c.fillRect(0,0,w,h)}const a=s.angle*Math.PI/180,pad=Math.min(w,h)*o.padding/100,bw=w-pad*2,bh=h-pad*2;c.translate(w/2,h/2);c.rotate(a);
 if(pad===0&&o.frame==='none'&&o.border===0){const co=Math.abs(Math.cos(a)),si=Math.abs(Math.sin(a)),scale=Math.max((w*co+h*si)/s.image.width,(w*si+h*co)/s.image.height)*s.zoom,sw=s.image.width*scale,sh=s.image.height*scale;c.drawImage(s.image,-sw/2+s.x*Math.max(0,(sw-w*co-h*si)/2),-sh/2+s.y*Math.max(0,(sh-w*si-h*co)/2),sw,sh);return}
 const chrome=o.frame==='browser'?Math.max(32,bw*.025):o.frame==='minimal'?12:0;
 c.fillStyle=o.borderColor;c.shadowColor='rgba(0,0,0,.24)';c.shadowBlur=o.shadow*2;c.shadowOffsetY=o.shadow/2;c.beginPath();c.roundRect(-bw/2,-bh/2,bw,bh,o.radius);c.fill();c.shadowColor='transparent';c.clip();c.fillStyle=o.frame==='browser'?'#f4f5f6':o.borderColor;c.fillRect(-bw/2,-bh/2,bw,bh);
 const x=-bw/2+o.border,y=-bh/2+chrome+o.border,iw=bw-2*o.border,ih=bh-chrome-2*o.border,scale=Math.max(iw/s.image.width,ih/s.image.height)*s.zoom,sw=s.image.width*scale,sh=s.image.height*scale;
 c.save();c.beginPath();c.rect(x,y,iw,ih);c.clip();c.drawImage(s.image,x+(iw-sw)/2+s.x*(sw-iw)/2,y+(ih-sh)/2+s.y*(sh-ih)/2,sw,sh);c.restore();
 if(chrome>15){['#e87c70','#dfb955','#66b68c'].forEach((color,i)=>{c.fillStyle=color;c.beginPath();c.arc(-bw/2+20+i*18,-bh/2+chrome/2,4.5,0,Math.PI*2);c.fill()});c.fillStyle='#6a7077';c.font=`${Math.max(11,chrome*.31)}px sans-serif`;c.textAlign='center';c.fillText(new URL(s.url).hostname,0,-bh/2+chrome*.62,bw*.5)}
}
export function filename(slug:string,s:Shot,o:Settings){return `${slug}-${s.index===0?'portada':'preview-'+s.index}.${o.format==='jpeg'?'jpg':o.format}`}
export async function encode(s:Shot,o:Settings){const c=document.createElement('canvas');draw(c,s,o,false);const mime='image/'+o.format;return new Promise<Blob>((res,rej)=>c.toBlob(b=>b&&b.type===mime?res(b):rej(Error('Formato no compatible con tu navegador. Prueba PNG.')),mime,o.quality/100))}
export function download(b:Blob,n:string){const a=document.createElement('a');a.download=n;a.href=URL.createObjectURL(b);a.click();setTimeout(()=>URL.revokeObjectURL(a.href),30000)}
function crc(b:Uint8Array){let c=0xffffffff;for(const n of b){c^=n;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0}
export async function zip(files:{name:string;blob:Blob}[]){const parts:BlobPart[]=[],central:BlobPart[]=[];let offset=0,cs=0;for(const f of files){const n=new TextEncoder().encode(f.name),d=new Uint8Array(await f.blob.arrayBuffer()),sum=crc(d);let h=new Uint8Array(30),v=new DataView(h.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint32(14,sum,true);v.setUint32(18,d.length,true);v.setUint32(22,d.length,true);v.setUint16(26,n.length,true);parts.push(h,n,d);h=new Uint8Array(46);v=new DataView(h.buffer);v.setUint32(0,0x02014b50,true);v.setUint16(4,20,true);v.setUint16(6,20,true);v.setUint32(16,sum,true);v.setUint32(20,d.length,true);v.setUint32(24,d.length,true);v.setUint16(28,n.length,true);v.setUint32(42,offset,true);central.push(h,n);cs+=46+n.length;offset+=30+n.length+d.length}const b=new Uint8Array(22),v=new DataView(b.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(8,files.length,true);v.setUint16(10,files.length,true);v.setUint32(12,cs,true);v.setUint32(16,offset,true);return new Blob([...parts,...central,b],{type:'application/zip'})}
